version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  backend:
    build:
      dockerfile: Dockerfile.backend
    ports:
      - 8000:8000
    depends_on:
      - mongodb

  frontend:
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000
    depends_on:
      - backend