FROM python:3.12.3
WORKDIR /backend
COPY /backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY /backend .
CMD python3 models/populate.py && uvicorn main:app --host 0.0.0.0 --port 8000