version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - ${PORT}:27017

  backend:
    build:
      dockerfile: Dockerfile.backend
    ports:
      - ${PORT}:8000
    depends_on:
      - mongodb

  frontend:
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - ${PORT}:80
    depends_on:
      - backend