volumes:
  postgres_data:
    driver: local
  jenkins_home:

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_ADDR: postgres
      DB_VENDOR: POSTGRES
      DB_DATABASE: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - 8080:8080
    command: start-dev

  backend:
    build:
      dockerfile: Dockerfile.backend
    environment:
      PORT: 8000
      HOST: 0.0.0.0
      MONGODB_SERVER_URL: mongodb://mongodb:27017/
      KEYCLOAK_REALM: GSS
      KEYCLOAK_CLIENT_ID: GSS
      KEYCLOAK_SERVER_URL: http://keycloak:8080/
      KEYCLOAK_CALLBACK_URI: http://backend:8000/docs
      KEYCLOAK_CLIENT_SECRET: 1E9n6y1auNuY1f4yvllTrAh9yulBMbP7
      KEYCLOAK_ADMIN_CLIENT_SECRET: xFdD90LEVtl4sAsXPtls1XJPW1zTUNSH
    ports:
      - 8000:8000

  frontend:
    build:
      dockerfile: Dockerfile.frontend
    environment:
      HOST: 0.0.0.0
    ports:
      - 4321:4321

  jenkins:
    image: jenkins/jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - 8081:8080
      - 50000:50000