volumes:
  postgres_data:
    driver: local

services:
  mongodb:
    image: mongo
    ports:
      - ${MONGODB_PORT}:27017

  postgres:
    image: postgres
    env_file:
      - path: .env
      - path: .env.override
        required: false
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak
    env_file:
      - path: .env
      - path: .env.override
        required: false
    # volumes:
    #   - ./ssl:/opt/keycloak/conf
    ports:
      - ${KEYCLOAK_PORT}:8080
    command: start-dev

  backend:
    build:
      dockerfile: Dockerfile.backend
    env_file:
      - path: .env
      - path: .env.override
        required: false
    ports:
      - ${BACKEND_PORT}:8000

  frontend:
    build:
      dockerfile: Dockerfile.frontend
    env_file:
      - path: .env
      - path: .env.override
        required: false
    ports:
      - ${FRONTEND_PORT}:4321

  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./ssl:/etc/nginx/ssl
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   ports:
  #     - 443:443