volumes:
  postgres_data:
    driver: local
  jenkins_home:

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_ADDR: postgres
      DB_VENDOR: POSTGRES
      DB_DATABASE: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - 8080:8080
    command: start-dev

  backend:
    build:
      dockerfile: Dockerfile.backend
    environment:
      PORT: 8000
      HOST: 0.0.0.0
      SSL_KEYFILE: /backend/ssl/private.key
      SSL_CERTFILE: /backend/ssl/certificate.crt
      MONGODB_SERVER_URL: mongodb://mongodb:27017/
      KEYCLOAK_REALM: GSS
      KEYCLOAK_CLIENT_ID: GSS
      KEYCLOAK_SERVER_URL: http://keycloak:8080/
      KEYCLOAK_CALLBACK_URI: http://backend:8000/docs
      KEYCLOAK_CLIENT_SECRET: k3v9rJM1dxlURjWVl9BppMAgNZaQchTk
      KEYCLOAK_ADMIN_CLIENT_SECRET: 8r0xgFmrqCCby0FpMzX0f50JDZa39c8c
    volumes:
      - ./ssl:/backend/ssl
    ports:
      - 8000:8000

  frontend:
    build:
      dockerfile: Dockerfile.frontend
    environment:
      PORT: 443
      HOST: 0.0.0.0
      SERVER_KEY_PATH: /frontend/ssl/private.key
      SERVER_CERT_PATH: /frontend/ssl/certificate.crt
      KEYCLOAK_SERVER_URL: http://keycloak:8080/
    volumes:
      - ./ssl:/frontend/ssl
    ports:
      - 443:443

  # jenkins:
  #   image: jenkins/jenkins
  #   volumes:
  #     - jenkins_home:/var/jenkins_home
  #   ports:
  #     - 8080:8080